// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALq62WBWRkpYIBLdqhLPSwvIMFhEFDVhQ',
    appId: '1:558958962928:web:ca74ccad315917d2347a35',
    messagingSenderId: '558958962928',
    projectId: 'polaris-dynamic-form-b8f13',
    authDomain: 'polaris-dynamic-form-b8f13.firebaseapp.com',
    storageBucket: 'polaris-dynamic-form-b8f13.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmEpHA6VHZZLC2UAsQA5ZoMW2FsUNwXY8',
    appId: '1:558958962928:android:a8948a748f98a73e347a35',
    messagingSenderId: '558958962928',
    projectId: 'polaris-dynamic-form-b8f13',
    storageBucket: 'polaris-dynamic-form-b8f13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHl1nUNuGcotQl8_PPLmBc8Nzh3jzfSe4',
    appId: '1:558958962928:ios:40ca2d6076b3c2c3347a35',
    messagingSenderId: '558958962928',
    projectId: 'polaris-dynamic-form-b8f13',
    storageBucket: 'polaris-dynamic-form-b8f13.appspot.com',
    iosBundleId: 'com.polaris.dynamicForm',
  );
}
